### ISSUE TITLE
We need update for 2.8

### ISSUE THREAD

**Issue by brothermechanic** [dfelinto/cork-on-blender#5]
Hello
Great addon for great booleans!
Please, update it for blender-2.8

**Comment by dfelinto** [comment]
Can you paste an error showing what is not working for 2.8? I don't have much time to dedicate to this addon, but I can't think of any parts of the API that I have used that would lead to an error. (try to manually change the blender required vision in the top of the __init__.py see if that allows the addon to run)

**Comment by brothermechanic** [comment]
Hello
Thank you for answer
If i install this addon to blender-2.8x - there is no interface (buttons), i can't test it
I try to test fork from https://github.com/A-Metaphysical-Drama
But don't susses
![Screenshot_20191003_1570064087](https://user-images.githubusercontent.com/3109995/66098411-57267680-e5c4-11e9-9ac0-0fc07121f123.jpg)
See on top, i heave cork installed
OFF exporter from https://github.com/A-Metaphysical-Drama too
![Screenshot_20191003_1570064116](https://user-images.githubusercontent.com/3109995/66098466-7d4c1680-e5c4-11e9-8afd-d57e2f25fc17.jpg)
And don't worked too )
In 2.7 all works super
![Screenshot_20191003_1570064169](https://user-images.githubusercontent.com/3109995/66098494-8fc65000-e5c4-11e9-925d-483a0a686933.jpg)
But... you know) it will be nice to have this booleans in 2.8
If you find time to fix, this will be very very useful not only for me
Thank you

**Comment by dfelinto** [comment]
You need to replace `context.user_preferences` with `context.preferences`
and `context.depsgraph` with `context.view_layer.depsgraph`

Em qui, 3 de out de 2019 às 01:02, brothermechanic <notifications@github.com>
escreveu:

**Comment by brothermechanic** [comment]
Thanks
Now looks like cork-on-blender start wirking
But
![Screenshot_20191003_1570097955](https://user-images.githubusercontent.com/3109995/66130304-536e1080-e613-11e9-9b7e-74b96cfbd445.jpg)
This is error of blender-off-addon
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.81/scripts/addons/blender-off-addon-master/__init__.py", line 160, in execute
    return save(self, context, **keywords)
  File "/home/bm/.config/blender/2.81/scripts/addons/blender-off-addon-master/__init__.py", line 271, in save
    mesh = obj.to_mesh(context.depsgraph, APPLY_MODIFIERS)
AttributeError: 'Context' object has no attribute 'depsgraph'

location: <unknown location>:-1

```
Can you help me fix it too, please?

**Comment by dfelinto** [comment]
This part is a tiny bit more complicated:

Replace `mesh = obj.to_mesh(context.depsgraph, APPLY_MODIFIERS)` with `mesh
= obj.evaluated_get(context.evaluated_depsgraph_get()).to_mesh()`

>

**Comment by brothermechanic** [comment]
Wow
Now works, but with issue
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.81/scripts/addons/cork-on-blender-cork-on-blender/__init__.py", line 170, in execute
    return self.exec(context)
  File "/home/bm/.config/blender/2.81/scripts/addons/cork-on-blender-cork-on-blender/__init__.py", line 174, in exec
    slice_out(context, self._cork, self._method, self._base, self._plane)
  File "/home/bm/.config/blender/2.81/scripts/addons/cork-on-blender-cork-on-blender/cork.py", line 83, in slice_out
    bpy.ops.import_mesh.off(filepath=filepath_result)
  File "/usr/share/blender/2.81/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/bm/.config/blender/2.81/scripts/addons/blender-off-addon-master/__init__.py", line 107, in execute
    scene.update()
AttributeError: 'Scene' object has no attribute 'update'

location: /usr/share/blender/2.81/scripts/modules/bpy/ops.py:201



location: <unknown location>:-1
```
![Screenshot_20191003_1570099384](https://user-images.githubusercontent.com/3109995/66131964-1f481f00-e616-11e9-97ba-adb3c9b6828f.jpg)

but now i can already use it!
Thank you!)

**Comment by dfelinto** [comment]
scene.update() should be replaced by context.view_layer.update()

**Comment by brothermechanic** [comment]
Cool, thank you.
I created 2 forks , may be it will be useful for someone, or you will update master)
https://github.com/brothermechanic

**Comment by Hmasterdm** [comment]
Thank you both for your work ! It's working well and help a lot when blender internal boolean doesn't work.
